-- -----------------------------------------------------
-- Table TB_USUARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_USUARIO (
  NI_COD_USUARIO INT NOT NULL,
  VC_NOME VARCHAR(150) NOT NULL,
  VC_CPF VARCHAR(11) NOT NULL,
  VC_EMAIL VARCHAR(45) NOT NULL,
  VC_SENHA VARCHAR(10) NOT NULL,
  NI_STATUS_USUARIO INT NOT NULL,
  DTH_CADASTRO TIMESTAMP NOT NULL,
  DTH_ATUALIZACAO TIMESTAMP NULL,
  PRIMARY KEY (NI_COD_USUARIO)
 );


-- -----------------------------------------------------
-- Table TB_ENDERECO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_ENDERECO (
  NI_COD_ENDERECO INT NOT NULL,
  NI_COD_USUARIO INT NOT NULL,
  VC_CEP VARCHAR(8) NOT NULL,
  VC_LOGRADOURO VARCHAR(45) NOT NULL,
  VC_BAIRRO VARCHAR(45) NOT NULL,
  VC_CIDADE VARCHAR(45) NOT NULL,
  VC_ESTADO VARCHAR(20) NOT NULL,
  NI_NUMERO INT NOT NULL,
  VC_COMPLEMENTO VARCHAR(50) NULL,
  
  PRIMARY KEY (NI_COD_ENDERECO),
  
  CONSTRAINT FK_TB_ENDERECO_USUARIO
    FOREIGN KEY (NI_COD_USUARIO)
    REFERENCES TB_USUARIO (NI_COD_USUARIO)
);


-- -----------------------------------------------------
-- Table TB_ROLE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_ROLE (
  NI_COD_ROLE INT NOT NULL,
  VC_ROLE VARCHAR(45) NOT NULL,
  PRIMARY KEY (NI_COD_ROLE)
);


-- -----------------------------------------------------
-- Table TB_ROLE_USUARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_ROLE_USUARIO (
  NI_COD_ROLE INT NOT NULL,
  NI_COD_USUARIO INT NOT NULL,
  
  PRIMARY KEY (NI_COD_ROLE, NI_COD_USUARIO),
 
  CONSTRAINT FK01_TB_ROLE_USUARIO
    FOREIGN KEY (NI_COD_ROLE)
    REFERENCES TB_ROLE (NI_COD_ROLE),
    
  CONSTRAINT FK02_TB_ROLE_USUARIO
    FOREIGN KEY (NI_COD_USUARIO)
    REFERENCES TB_USUARIO (NI_COD_USUARIO)
    
);


-- -----------------------------------------------------
-- Table TB_CATEGORIA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_CATEGORIA (
  NI_COD_CATEGORIA INT NOT NULL,
  VC_DESC_CATEGORIA VARCHAR(45) NOT NULL,
  PRIMARY KEY (NI_COD_CATEGORIA)
);


-- -----------------------------------------------------
-- Table TB_MARCA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_MARCA (
  NI_COD_MARCA INT NOT NULL,
  VC_DESC_MARCA VARCHAR(45) NOT NULL,
  PRIMARY KEY (NI_COD_MARCA)
);


-- -----------------------------------------------------
-- Table TB_MODELO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_MODELO (
  NI_COD_MODELO INT NOT NULL,
  VC_DESC_MODELO VARCHAR(45) NOT NULL,
  PRIMARY KEY (NI_COD_MODELO)
);


-- -----------------------------------------------------
-- Table TB_VEICULO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_VEICULO (
  NI_COD_VEICULO INT NOT NULL,
  VC_DESC_CAMBIO VARCHAR(45) NOT NULL,
  NI_ANO_VEICULO INT NOT NULL,
  NI_IND_GARANTIA_FAB INT NOT NULL,
  NI_NUM_QUILOMETRAGEM VARCHAR(45) NOT NULL,
  VC_DESC_PLACA VARCHAR(45) NOT NULL,
  ND_VALOR DECIMAL(10,2) NOT NULL,
  VC_ESTADO VARCHAR(45) NOT NULL,
  VC_CIDADE VARCHAR(100) NOT NULL,
  NI_COD_CATEGORIA INT NOT NULL,
  NI_COD_MARCA INT NOT NULL,
  NI_COD_MODELO INT NOT NULL,
  NI_COD_USUARIO INT NOT NULL,
  NI_STATUS_VEICULO INT NOT NULL,
  DTH_INCLUSAO TIMESTAMP NOT NULL,
  DTH_ATUALIZACAO TIMESTAMP NULL,
  DTH_VENDA TIMESTAMP NULL,
  
  PRIMARY KEY (NI_COD_VEICULO),
  
  CONSTRAINT FK_TB_VEICULO_CATEGORIA
    FOREIGN KEY (NI_COD_CATEGORIA)
    REFERENCES TB_CATEGORIA (NI_COD_CATEGORIA),
    
  CONSTRAINT FK_TB_VEICULO_MARCA
    FOREIGN KEY (NI_COD_MARCA)
    REFERENCES TB_MARCA (NI_COD_MARCA),
    
  CONSTRAINT FK_TB_VEICULO_TB_MODELO
    FOREIGN KEY (NI_COD_MODELO)
    REFERENCES TB_MODELO (NI_COD_MODELO),
    
  CONSTRAINT FK_TB_VEICULO_USUARIO
    FOREIGN KEY (NI_COD_USUARIO)
    REFERENCES TB_USUARIO (NI_COD_USUARIO)
    
);


-- -----------------------------------------------------
-- Table TB_ITEM_VEIC
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_ITEM_VEIC (
  NI_COD_ITEM INT NOT NULL,
  VC_DESC_ITEM VARCHAR(45) NOT NULL,
  NI_STATUS_REGISTRO INT NOT NULL DEFAULT 1,
  PRIMARY KEY (NI_COD_ITEM)
);


-- -----------------------------------------------------
-- TB_VEICULO_ITEM_VEIC
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_VEICULO_ITEM_VEIC (
  NI_COD_VEICULO INT NOT NULL,
  NI_COD_ITEM INT NOT NULL,
  PRIMARY KEY (NI_COD_VEICULO, NI_COD_ITEM),
  
  CONSTRAINT FK01_TB_VEICULO_ITEM_VEIC 
    FOREIGN KEY (NI_COD_VEICULO)
    REFERENCES TB_VEICULO (NI_COD_VEICULO),
  
   CONSTRAINT FK02_TB_VEICULO_ITEM_VEIC
    FOREIGN KEY (NI_COD_ITEM)
    REFERENCES TB_ITEM_VEIC (NI_COD_ITEM)
   
);


-- -----------------------------------------------------
-- Table TB_ARQUIVO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_ARQUIVO (
  NI_COD_ARQUIVO INT NOT NULL,
  VC_END_ARQUIVO VARCHAR(150) NOT NULL,
  PRIMARY KEY (NI_COD_ARQUIVO)
);


-- -----------------------------------------------------
-- Table TB_VEICULO_ARQUIVO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TB_VEICULO_ARQUIVO (
  NI_COD_VEICULO INT NOT NULL,
  NI_COD_ARQUIVO INT NOT NULL,
  
  PRIMARY KEY (NI_COD_VEICULO, NI_COD_ARQUIVO),
  
  CONSTRAINT FK01_TB_VEICULO_ARQUIVO
    FOREIGN KEY (NI_COD_VEICULO)
    REFERENCES TB_VEICULO (NI_COD_VEICULO),
   
   
  CONSTRAINT FK02_TB_VEICULO_ARQUIVO
    FOREIGN KEY (NI_COD_ARQUIVO)
    REFERENCES TB_ARQUIVO (NI_COD_ARQUIVO)
);




